server:
  port: 7005
eureka:
  instance:
#    hostname: localhost  #单机
    hostname: eureka7005.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/
